### ISSUE TITLE
Fonction «put the digital pin 1 to logic state HIGH»

### ISSUE THREAD

**Issue by Tournesol01** [A-S-T-U-C-E/STudio4Education#28]
Ce bloc est très encombrant dans le sens de la hauteur, à cause de l'image qu'il contient.
Un simple programme «Blink» prend donc énormément de place.

Pourquoi encombrer ce bloc avec une image, qui d'ailleurs ne traduit pas le comportement de la fonction ?
l'image représente une impulsion. Or  «put the digital pin 1 to logic state HIGH» concerne un flanc montant.

Ou alors...
Pourquoi ne pas afficher 2 icônes différentes :

- une icône «flanc montant» quand state = HIGH ;
- une icône «flanc descendant» quand state = LOW.

Ça, ce serait chouette !

Par contre, il faut absolument garder les icônes pour les fonctions «write about analog pin...» qui traduisent bien la réalité.
Pour être encore plus conforme à la réalité, il faudrait remplacer «write about analog pin...» par «write about PWM pin...» ou «actuate PWM pin 1 with value 127» ou «adjust value of PWM pin 1 to 127».

**Comment by SebCanet** [comment]
Fixed.

**Comment by Tournesol01** [comment]
J'aime bien la nouvelle mouture avec le «1» ou le «0»

**Comment by SebCanet** [comment]
Cool ! 'est validé alors, je peux continuer à améliorer grâce à tes remarques !
