### ISSUE TITLE
Catégories qui disparaissent

### ISSUE THREAD

**Issue by Tournesol01** [A-S-T-U-C-E/STudio4Education#30]
Sur la version «locale».
Après avoir choisi une carte, si on fait «F5» ou qu'on rafraîchit l'URL, toutes les catégories en-dessous de «Board» disparaissent.

Sur la version «on line», on obtient l'erreur «404».

**Comment by SebCanet** [comment]
Le comportement "normal" maintenant est de n'avoir que le strict minimum (juste algo, ou bien algo + carte si carte choisie) ensuite l'utilisateur doit cocher dans la liste les catégories qu'il souhaite utiliser.

**Comment by Tournesol01** [comment]
OK.
Ça fonctionne bien.

... et j'aime bien cette stratégie qui consiste à ne faire apparaître (choisir) que les suppléments dont on a besoin.
