### ISSUE TITLE
Doublon (dans «Board / ...») du bloc «créer une liste avec...» et pertinence du libellé «créer»

### ISSUE THREAD

**Issue by Tournesol01** [A-S-T-U-C-E/STudio4Education#38]
Ce bloc est présent dans deux catégories :

- Board / Sérial communication ;
- Board / Network data.

N'y a-t-il pas redondance ?

Dans les deux cas le code généré est le même :

  Serial.print(null);
  Serial.print(';');
  Serial.print(null);
  Serial.println();

Ce code apparaît dans «void loop()».

Il s'agit d'une SORTIE en direction du moniteur.
Pourquoi alors avoir nommé ce bloc «créer une liste avec...» ?
Un libellé plus approprié me semble être : «imprimer une liste avec...».

Ou alors :

- on créé effectivement une liste avec plusieurs éléments automatiquement séparés par un « ; »  (et pourquoi pas le choix du séparateur ? ) ;
- on a la possibilité d'AFFECTER UN NOM à cette liste ;
- la liste peut être déposée soit dans le «setup», soit être générée au besoin quelque part dans «void loop()» ;
- ⇒ cette liste nommée peut ainsi être imprimée et ré-employée plus qu'une fois au gré des besoins, comme un message.

**Comment by SebCanet** [comment]
Travail en cours d'utilisation des websockets.
