### ISSUE TITLE
Plein écran et retour : disparition du volet «Detailed compilation verbose»

### ISSUE THREAD

**Issue by Tournesol01** [A-S-T-U-C-E/STudio4Education#42]
(testé dans Opera et dans Edge)

Premier cas : 

- on a éventuellement placé des blocs sur l'espace de travail, choisi une carte, etc., 
- MAIS ON N'A PAS modifié la taille du volet «Detailed compilation verbose» ;
- on passe en plein écran 

⇒ pendant un court instant (fugitif) le volet «Detailed compilation verbose» s'agrandit en hauteur (environ 2cm) puis redevient à sa taille minimale.

- on quitte ensuite le mode plein écran...

⇒ le volet «Detailed compilation verbose» n'est plus visible. Il est masqué par la barre de tâches.

Deuxième cas :

- on passe en mode plein écran (après avoir rechargé ST4 pour être dans les conditions de départ) ;
- on augmente à peine la hauteur du bandeau «Detailed compilation verbose»...
⇒ quand on quitte le mode plein écran, le bandeau est caché par la barre de tâches.

Troisième cas (fonctionnement correct) :

- on passe en mode plein écran (après avoir rechargé ST4 pour être dans les conditions de départ) ;
- on augmente la hauteur du bandeau «Detailed compilation verbose» de plus de 25 mm (je n'ai pas la correspondance en pixels sur mes écrans).
⇒ quand on quitte le mode plein écran, le bandeau RESTE VISIBLE au-dessus de la barre de tâches, avec son «ascenseur horizontal».
Sa hauteur semble dépendre proportionnellement de la hauteur qu'on avait réglée en mode plein écran.

Quatrième cas : (fonctionnement correct)

- on recharge ST4 ;
- en mode écran normal, on retouche la hauteur du bandeau «Detailed compilation verbose», ne serait-ce que de quelques pixels EN PLUS ou EN MOINS ;
- on passe en mode plein écran
⇒ le bandeau «Detailled compilation verbose» mesure environ 3cm en hauteur. Parfait.
⇒ de retour au mode normal, LE BANDEAU RESTE VISIBLE, mais à sa taille réduite (?)
⇒ un nouvel aller-retour montre ce même comportement du bandeau. 

Ces deux derniers cas peuvent être admis comme satisfaisants.
Cependant, quand on passe d'un mode à l'autre, pourquoi ne pas conserver la taille du bandeau à la valeur exacte qu'on a réglée, que ce soit depuis le mode plein écran ou depuis le mode normal ?
Car après tout, si dans l'un ou l'autre mode il nous a paru nécessaire d'agrandir ce bandeau, le passage d'un mode à l'autre n'annule pas forcément cette nécessité.
Il est toujours temps pour l'utilisateur, après avoir changé de mode dans un sens ou dans l'autre, de décider s'il conserve ou pas le bandeau à la taille qu'il lui a affectée.

**Comment by SebCanet** [comment]
Je le clos pour l'instant car j'ai trouvé une solution aux pb de masquage.
Pour le pb de conserver les tailles, ce n'est pas possible car il faudrait qu'une taille détermine les autres au passage en "hors plein écran". Et là on ne peut pas présager de ce que veut l'utilisateur...
une solution serait de passer en mode 'flex' et là les 3 cadres (block / code / console) garderaient leur proportionnalité par rapport à la taille de l'écran.
