### ISSUE TITLE
Dysfonctionnement de la corbeille quand on passe en mode plein écran ou qu'on le quitte

### ISSUE THREAD

**Issue by Tournesol01** [A-S-T-U-C-E/STudio4Education#43]
Si on passe en mode plein écran et qu'on ne retouche pas les blocs qu'on a déposés en mode normal, le couvercle de la corbeille ne s'ouvre pas quand on cherche à jeter un bloc (ou groupe de blocs). La corbeille ne fonctionne pas.

Par contre, partant de cette situation, si en mode plein écran on AJOUTE au moins un bloc à celui ou ceux existants, la corbeille se remet à fonctionner.
Si on commence à ajouter des blocs seulement après être passé en mode plein écran, la corbeille fonctionne.

On a exactement le même phénomène quand on part du mode plein écran et qu'on revient en mode normal ⇒ la corbeille ne fonctionne pas, tant qu'on n'AJOUTE PAS AU MOINS UN BLOC.

Si on SUPPRIME un bloc (ou plusieurs) avec la touche «Suppr.», la corbeille continue de ne pas fonctionner.

**Comment by SebCanet** [comment]
Problème réglé.
