### ISSUE TITLE
Développer un sketch sur plusieurs onglets

### ISSUE THREAD

**Issue by Tournesol01** [A-S-T-U-C-E/STudio4Education#57]
### Discussed in https://github.com/A-S-T-U-C-E/STudio4Education/discussions/55

<div type='discussions-op-text'>

<sup>Originally posted by **Tournesol01** November 16, 2021</sup>
Cerise sur le gâteau (mais là je rêve un peu)...

... et si UN sketch pouvait être développé en utilisant plusieurs onglets ?

En effet, un des inconvénients des blockly de tout poil, c'est que, aussitôt que le sketch se complexifie (et on y arrive très vite, même avec des sujets simples), sa visibilité devient catastrophique :
⇒ l'écran ne peut plus tout contenir ni tout montrer de façon confortable ;
⇒ des parties entières du sketch doivent par conséquent être déplacées hors de la vue («Collapse block» ne suffit pas toujours) et parfois on ne se rappelle plus si on les a toutes glissées à droite ou en bas... (faute de cartographie du projet et faute à notre mémoire). C'est assez pénible d'errer à la recherche des blocs qu'on a éloignés.

Avec plusieurs onglets nommés on pourrait :

- travailler sur 2 ou 3 sketchs en parallèle, ou créer un sketch en puisant des éléments dans le ou les autres onglets (grâce à un «copier-coller» bien sûr ;
- utiliser un onglet comme «bag» pour le ou les autres sketchs ⇒ l'accessibilité aux blocs mis de côté serait très confortable et rapide : un seul clic suffit pour basculer vers un onglet quelconque.
- idéalement le «coller» du «copier-coller» déposerait les blocs à l'endroit du pointeur. Génial ;

Si en plus on a la possibilité de déclarer que 2 OU 3 OU 4 ONGLETS SONT AFFECTES AU MEME SKETCH, alors là, on nage dans le bonheur : on peut bâtir des projets d'envergure avec une structuration confortable du visuel.
Par exemple :

- un premier onglet (présent d'office) contient la partie «void loop( )» ;
- un 2e ONGLET PERMANENT contiendrait le code C++ ⇒ plus besoin du volet extensible de droite pour afficher le code, et qui vient réduire la zone de travail (qu'on veut la plus grande possible). Un clic ⇒ on voit le code ; un clic ⇒ on revient à n'importe quel autre onglet.
- un autre onglet, ajouté, peut contenir les déclarations (qui sont parfois très conséquentes donc encombrantes et sur lesquelles on travaille peu) ;
- un autre encore (ou plusieurs autres) ajoutés, contiennent les fonctions personnelles (sous-programmes)...

... et là, on aurait une application très innovante.

Elle l'est déjà par bien des aspects.
Alors, considérant que, telle qu'elle est prévue, il n'y a plus obligatoirement besoin de recourir à l'IDE extérieur, pourquoi ne pas rendre S4E unique en son genre, et incontournable ? 
Un vrai outil de développement, pas réservé uniquement à l'éducation.

Son aspect, au premier coup d'oeil, rappellerait le concept «blockly», mais S4E se démarquerait par son ergonomie, ses fonctionnalités et sa richesse.

L'élaboration de projets un tant soit peu complexes deviendrait vraiment amusante, confortable, efficace et attrayante.

... mais pour les débutants et les tous petits projets, on pourrait toujours travailler avec seulement les 2 onglets de base :

- un pour les blocs ;
- un pour le code.</div>

**Comment by SebCanet** [comment]
Doublon avec le #57, et tant que la demande n'est pas finalisée, merci de laisser les idées maturer dans la partie "Discussions".
