### ISSUE TITLE
DÉBARASSER L'ESPACE DE TRAVAIL DE TOUTES SES ICONES

### ISSUE THREAD

**Issue by Tournesol01** [A-S-T-U-C-E/STudio4Education#60]
### Discussed in https://github.com/A-S-T-U-C-E/STudio4Education/discussions/51

<div type='discussions-op-text'>

<sup>Originally posted by **Tournesol01** November 16, 2021</sup>
Autre suggestion

... et finalement, si on débarrassait complétement l'espace de travail de ses icônes, pour que tout l'espace soit réservé... au travail ?
D'autant plus logique qu'une icône dans le bandeau bleu permet de réduire la tool box !

En effet, les icônes «undo», «redo», «ajuster à l'écran», «centrage du sketch», «zoom +» et «zoom -» peuvent très avantageusement figurer dans le bandeau supérieur.
On évite ainsi, comme pour la corbeille, de se trouver dans l'impossibilité d'accéder à l'une ou l'autre de ces icônes parce qu'elle est masquée par des blocs du sketch en cours.

Cela étant dit, on peut même se passer des icônes «undo» et «redo» (si la place manque dans le bandeau).
En effet, «ctrl-Z» et «ctrl-Y» sont des standards de Windows et sont plus rapides à utiliser que les icônes.

En fait, seules les icônes «centrage», «ajuster à l'écran», «zoom -» et «zoom +» sont à conserver et à disposer dans le bandeau supérieur.
Cela ne gênerait pas l'apparition des messages d'identification des fonctionnalités.
(Cela dit, la roulette centrale de la souris est déjà utilisée pour zoomer avant ou arrière)</div>

**Comment by SebCanet** [comment]
Ce n'est pas un Issue, mais une discussion à poursuivre, il faut trancher avant.
