### ISSUE TITLE
Dysfonctionnement de UNDO avec la fonction logique «Switch case»

### ISSUE THREAD

**Issue by Tournesol01** [A-S-T-U-C-E/STudio4Education#65]
Le défaut décrit ci-dessous apparaît indifféremment si on utilise l'icône «UNDO» ou si on utilise «ctrl-Z»

– fonctionnement normal :
On choisit un bloc quelconque dans une catégorie. Un simple clic sur son icône le dépose sur le workspace.
Si maintenant on fait «ctrl-Z» ou «UNDO», le bloc disparait. On annule bien l'action de choix du bloc.

– premier cas de dysfonctionnement :
On choisit précisément le bloc «Switch case» et on le dépose sur le workspace, soit d'un simple clic, soit par drag&drop.
Le bloc se cale sur la grille.
⇒ «UNDO» ramène le bloc à la position où il a été déposé (petit déplacement) : le bloc quitte la grille ;
⇒ un second «UNDO» ne fait rien : **le bloc ne disparaît pas d'où il est venu.**

– première conséquence : 
On choisit un nouveau bloc quelconque (mais pas «Switch case») et on le dépose par un simple clic ou par drag&drop.
⇒ «UNDO» ramène ce nouveau bloc à la position où il a été déposé (petit déplacement) : le bloc quitte la grille ;
⇒ un second «UNDO» ne fait rien : le bloc ne disparaît pas d'où il est venu, contrairement cas de fonctionnement normal ci-dessus.

– deuxième conséquence : 
On met les deux blocs dans la poubelle.
On re-choisit le bloc «Switch case».
⇒ un premier «UNDO» repositionne le bloc hors de la grille (petit déplacement) ;
⇒ un 2e «UNDO» provoque la DUPLICATION du bloc «Switch case» et dispose les deux exemplaires de «Switvh case» de façon aléatoire sur le workspace.
Parfois le hasard fait que les deux blocs sont parfaitement SUPERPOSÉS, faisant croire que tout a fonctionné normalement !

– troisième conséquence : 
Suivant l'ordre dans lequel le bloc «switch case» et un autre bloc sont amenés sur le workspace, «UNDO» permettra à cet autre bloc de retourner d'où il vient... ou pas.

**Comment by SebCanet** [comment]
Normalement réglé. Merci de confirmer.

**Comment by Tournesol01** [comment]
OK. 
J'ai vérifié les différentes manips ⇒ le fonctionnement de UNDO est correct.
