### ISSUE TITLE
Reset S4E : erreur 404 toujours

### ISSUE THREAD

**Issue by Tournesol01** [A-S-T-U-C-E/STudio4Education#67]
L'issue #41 «Reset S4E ⇒ erreur 404» semble ne pas avoir été résolue : 

En effet, si on choisit une carte et qu'ensuite on rafraîchit la page, on obtient une «erreur 404, file not found».

Le fait de sélectionner une carte ajoute «a-s-t-u-c-e.github.io/STudio4Education/?board=ESP_esp8266&level=skill1» à l'adresse de la page «https://a-s-t-u-c-e.github.io/STudio4Education».

La barre d'URL affiche donc : 

https://a-s-t-u-c-e.github.io/STudio4Education/a-s-t-u-c-e.github.io/STudio4Education/?board=ESP_esp8266&level=skill1

Il est donc normal d'obtenir une erreur 404.

**Comment by SebCanet** [comment]
Normalement c'est réglé !

**Comment by Tournesol01** [comment]
C'est OK.
