### ISSUE TITLE
S4E Electron - icônes «enregistrer» et «ouvrir»

### ISSUE THREAD

**Issue by Tournesol01** [A-S-T-U-C-E/STudio4Education#79]
En mode «novice» les deux icônes «enregistrer» et «ouvrir» sont affichées.
Dans les modes «skilled» et «expert», les icônes ne sont pas affichées, rendant impossible la sauvegarde des projets.
![S4E-6](https://user-images.githubusercontent.com/19183601/157062186-960fdb74-ca77-45d1-a1b0-91704f0152da.png)
![S4E-6A](https://user-images.githubusercontent.com/19183601/157062214-bd48d061-9805-4c2d-ab78-f13ffaea1c17.png)
.

**Comment by SebCanet** [comment]
Pour les élèves dont le niveau grimpe, l'accessibilité autorise l'utilisation de mnus déroulants, et actuellement l'icone du menu déroulant soit les 3 petites barres l'une au dessus de l'autre, soit les 3 petits points, comme ici en haut à gauche.

**Comment by Tournesol01** [comment]
OK.
Très pratique pour les débutants.
Alors pourquoi SUPPRIMER ce côté pratique pour les non débutants et leur faire perdre un peu de temps à chaque enregistrement ?
Une homogéneïté des commandes de base n'est-elle pas plus logique et préférable ?

Dans cette même optique, pourquoi «Undo» et «Redo» sont dans le bandeau supérieur en mode novice, ce qui est TRES PRATIQUE, alors que pour les 2 autres niveaux, les icône viennent encombrer le plan de travail, et, par la même occasion, agacer l'utilisateur «Skilled» ou «Expert» dont les programmes souvent plus conséquents viennent masquer ces icônes et gêner leur utilisation.
... ou encore : «comment faire compliqué, alors qu'on peut faire simple ?»

**Comment by SebCanet** [comment]
La réglementation dit qu'on peut s'autoriser les menus déroulants avec des utilisateurs non néophytes, et comme le nombre d’icônes croît avec les fonctionnalités, la barre risque d'être surchargée et le texte au survol ne plus apparaître. Il faut pnser que cela dépend de la résolution des écrans utilisés.
En ce qui concerne les icones sur le plan de travail, je me pose la question de les enfermer dans un 'coffre' qui s'ouvrirait à la demande pour accéder à ces fonctions ? Pour les niveaux 2 et 3, est ce utile ???
Je veux bien réouvrir le ticket pour examiner d'autres solutions...
