### ISSUE TITLE
S4E Electron - changement de langue et fond d'écran

### ISSUE THREAD

**Issue by Tournesol01** [A-S-T-U-C-E/STudio4Education#80]
Dans «Setup», lorsqu'on change de langue, le fond d'écran passe en bleu nuit.
«F5» rafraîchit l'écran : fond d'écran, icônes, catégories latérales ⇒ OK.
MAIS : 
– les blocs en cours sont perdus ;
– le port de communication est désélectionné ;
⇒ on a perdu le travail en cours.
![S4E-6B](https://user-images.githubusercontent.com/19183601/157077706-e728cb24-69ad-452d-8111-ca48973fc086.png)
.

**Comment by SebCanet** [comment]
Fixed in v0.9.6
