### ISSUE TITLE
S4E Electron - «Simulateur de circuits» ne s'ouvre pas

### ISSUE THREAD

**Issue by Tournesol01** [A-S-T-U-C-E/STudio4Education#81]
L'icône correspondante ne déclenche pas l'ouverture du simulateur de circuits.

En fait, le simulateur s'est ouvert une fois, je ne sais pas dans quelle circonstance, et depuis, plus rien.

**Comment by SebCanet** [comment]
Fixed in v0.9.6

**Comment by Tournesol01** [comment]
Désolé.
En mode «Expert», le simulateur de circuits ne s'ouvre toujours pas.

**Comment by SebCanet** [comment]
En local ou bien via Github ? Avec quel navigateur ?
